---
name: Terraform Module Release

on:
  workflow_call:
    inputs:
      version:
        description: "The version being released (e.g., v1.0.0)"
        required: true
        type: string

      module-name:
        description: "The name of the module being released (for multi-module repos only). If not specified, the entire repo will be released."
        default: ''
        required: false
        type: string

# NOTE: This declaration defaults all GH other permissions to none.
# - Create subsequent permissions scoped to job only after confirming with a techlead
# - Declaration here follows the policy defined in ADR-EA007
permissions:
  contents: none # Set so other permissions take the value 'none' by default
  id-token: none # Prevent OIDC token generation (‘none’ is the default)
  packages: none # Prevent package access (‘none’ is the default)

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Clone repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          sparse-checkout: ${{ inputs.module-name != '' && inputs.module-name || null }}
          sparse-checkout-cone-mode: false

      - name: Zip module files
        id: vars
        shell: pwsh
        run: |
          if ([string]::IsNullOrWhiteSpace('${{ inputs.module-name }}')) {
            Write-Output -InputObject "Module name not specified, releasing entire repo."
            $compress = @{
              Path = './*.*'
              DestinationPath = 'repo_${{ inputs.version }}.zip'
              Passthru = $true
            }
          } else {
            Write-Output -InputObject "Module name specified: ${{ inputs.module-name }}. Releasing only files in that directory."
            $compress = @{
              Path = './${{ inputs.module-name }}/*.*'
              DestinationPath = '${{ inputs.module-name }}_${{ inputs.version }}.zip'
              Passthru = $true
            }
          }

          $zipFileName = Compress-Archive @compress |
          Select-Object -ExpandProperty Name

          Write-Output -InputObject "ZIP_FILE_NAME=$zipFileName" |
          Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v2
        with:
          generate_release_notes: true
          name: ${{ inputs.module-name != '' && format('{0} {1}', inputs.module-name, inputs.version) || format('Repo {0}', inputs.version) }}
          files: ${{ steps.vars.outputs.ZIP_FILE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
